# Color Contrast In openCV

#### Import Libraries

In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

In [7]:
# Read/load Imput image
input_image = cv2.imread(r'D:\Computer-Vision-Bootcamp\images\wall1.jpg')
cv2.imshow('Orginal Image', input_image )

# Matrix of ones which is multipled by a scaler value of 60, matrix has dimesions same as out input image
Intensity_Matrix = np.ones(input_image.shape, dtype = 'uint8')*60

# Print Intensity Matrix
print(Intensity_Matrix)

# Add Intensity Matrix to input image in order to increase the brightness
bbrightened_image = cv2.add(input_image,Intensity_Matrix )
cv2.imshow('Bright', input_image)

#Subtract Intensity Matrix from input image in order to decrease the brightness
darkended_image = cv2.subtract(input_image, Intensity_Matrix)
cv2.imshow('Dark', input_image)

cv2.waitKey(0)
cv2.destroyAllWindows()

[[[60 60 60]
  [60 60 60]
  [60 60 60]
  ...
  [60 60 60]
  [60 60 60]
  [60 60 60]]

 [[60 60 60]
  [60 60 60]
  [60 60 60]
  ...
  [60 60 60]
  [60 60 60]
  [60 60 60]]

 [[60 60 60]
  [60 60 60]
  [60 60 60]
  ...
  [60 60 60]
  [60 60 60]
  [60 60 60]]

 ...

 [[60 60 60]
  [60 60 60]
  [60 60 60]
  ...
  [60 60 60]
  [60 60 60]
  [60 60 60]]

 [[60 60 60]
  [60 60 60]
  [60 60 60]
  ...
  [60 60 60]
  [60 60 60]
  [60 60 60]]

 [[60 60 60]
  [60 60 60]
  [60 60 60]
  ...
  [60 60 60]
  [60 60 60]
  [60 60 60]]]
